export const authConstants = {
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_FAILURE: "LOGIN_FAILURE",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGOUT_REQUEST: "LOGOUT_REQUEST",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
	LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const categoriesConstants = {
	GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
	GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
	GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
};
