export const authConstants = {
	LOGIN_REQUEST: "LOGIN_REQUEST",
	LOGIN_FAILURE: "LOGIN_FAILURE",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGOUT_REQUEST: "LOGOUT_REQUEST",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
	LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const categoriesConstants = {
	GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
	GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
	GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
	ADD_NEW_CATEGORIES_REQUEST: "ADD_NEW_CATEGORIES_REQUEST",
	ADD_NEW_CATEGORIES_SUCCESS: "ADD_NEW_CATEGORIES_SUCCESS",
	ADD_NEW_CATEGORIES_FAILURE: "ADD_NEW_CATEGORIES_FAILURE",
};

export const productsConstants = {
	GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
	GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
	GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
	ADD_NEW_PRODUCTS_REQUEST: "ADD_NEW_PRODUCTS_REQUEST",
	ADD_NEW_PRODUCTS_SUCCESS: "ADD_NEW_PRODUCTS_SUCCESS",
	ADD_NEW_PRODUCTS_FAILURE: "ADD_NEW_PRODUCTS_FAILURE",
};
